/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuInicial;

import ClientesClass.AgregarEmpresa;
import RecepcionPedidos.Formulario_Recepcion;
import javax.swing.JOptionPane;

/* @author Jefferson Torres */
public class PanelMenu extends javax.swing.JFrame {
    InfoRubbers infoRubbers = new InfoRubbers();
    AgregarEmpresaPanel agregarEmpresaPanel = new AgregarEmpresaPanel();
    AgregarClientePanel agregarClientePanel= new AgregarClientePanel();
    Formulario_Recepcion formulario_Recepcion = new Formulario_Recepcion();
    DetalleCotizarPanel detalleCotizarPanel = new DetalleCotizarPanel();
    ListaGuiasActivasPanel listaGuiasActivasPanel =new ListaGuiasActivasPanel();
    ListaGuiasCerradasPanel listaGuiasCerradasPanel =new ListaGuiasCerradasPanel();
    ListadosGuiasPanel listadosGuiasPanel =new ListadosGuiasPanel();
    public PanelMenu() 
    {
        initComponents();
        this.setTitle("Rubbers/ Menús Administración");
        this.setLocationRelativeTo(PanelMenu.this); 
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        PanelDeEscritorio = new javax.swing.JDesktopPane();
        BarraMenu = new javax.swing.JMenuBar();
        BtnRubbers = new javax.swing.JMenu();
        MenuGuias = new javax.swing.JMenu();
        btnGuiasActivas = new javax.swing.JMenuItem();
        btnGuiasCerradas = new javax.swing.JMenuItem();
        btnTodasLasGuias = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        BuscarCliente = new javax.swing.JMenuItem();
        AgregarClientes = new javax.swing.JMenu();
        AddClienteEmpresa = new javax.swing.JMenuItem();
        AddClienteNatural = new javax.swing.JMenuItem();
        MenuAlmacen = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        BtnCotizar = new javax.swing.JMenu();
        BtnRecepcion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout PanelDeEscritorioLayout = new javax.swing.GroupLayout(PanelDeEscritorio);
        PanelDeEscritorio.setLayout(PanelDeEscritorioLayout);
        PanelDeEscritorioLayout.setHorizontalGroup(
            PanelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        PanelDeEscritorioLayout.setVerticalGroup(
            PanelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDeEscritorio)
                .addContainerGap())
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDeEscritorio)
                .addContainerGap())
        );

        BtnRubbers.setText("Rubbers");
        BtnRubbers.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                BtnRubbersMenuSelected(evt);
            }
        });
        BtnRubbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRubbersActionPerformed(evt);
            }
        });
        BarraMenu.add(BtnRubbers);

        MenuGuias.setText("Guias");

        btnGuiasActivas.setText("Guias Activas");
        btnGuiasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiasActivasActionPerformed(evt);
            }
        });
        MenuGuias.add(btnGuiasActivas);

        btnGuiasCerradas.setText("Guias Cerradas");
        MenuGuias.add(btnGuiasCerradas);

        btnTodasLasGuias.setText("Todas las Guias");
        MenuGuias.add(btnTodasLasGuias);

        BarraMenu.add(MenuGuias);

        MenuClientes.setText("Clientes");

        BuscarCliente.setText("Buscar Cliente");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(BuscarCliente);

        AgregarClientes.setText("Registrar Cliente");
        AgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClientesActionPerformed(evt);
            }
        });

        AddClienteEmpresa.setText("Empresa");
        AddClienteEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClienteEmpresaActionPerformed(evt);
            }
        });
        AgregarClientes.add(AddClienteEmpresa);

        AddClienteNatural.setText("Persona");
        AddClienteNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClienteNaturalActionPerformed(evt);
            }
        });
        AgregarClientes.add(AddClienteNatural);

        MenuClientes.add(AgregarClientes);

        BarraMenu.add(MenuClientes);

        MenuAlmacen.setText("Almacén");

        jMenuItem1.setText("Ver Almacen");
        MenuAlmacen.add(jMenuItem1);

        jMenuItem2.setText("Actualizar Almacen");
        MenuAlmacen.add(jMenuItem2);

        BarraMenu.add(MenuAlmacen);

        BtnCotizar.setText("Cotizar");
        BtnCotizar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                BtnCotizarMenuSelected(evt);
            }
        });
        BarraMenu.add(BtnCotizar);

        BtnRecepcion.setText("Recepción Pedidos");
        BtnRecepcion.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                BtnRecepcionMenuSelected(evt);
            }
        });
        BtnRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecepcionActionPerformed(evt);
            }
        });
        BarraMenu.add(BtnRecepcion);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarClienteActionPerformed

    private void AddClienteNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClienteNaturalActionPerformed
       if(!agregarClientePanel.isShowing())
	{   
            PanelDeEscritorio.add(agregarClientePanel);
            agregarClientePanel.show();
	}
	else
	{
            JOptionPane.showMessageDialog(PanelDeEscritorio, "Ventana Abierta");
	}
    }//GEN-LAST:event_AddClienteNaturalActionPerformed

    private void btnGuiasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiasActivasActionPerformed
        if(!infoRubbers.isShowing())
	{   
            PanelDeEscritorio.add(infoRubbers);
            infoRubbers.show();
	}
	else
	{
            JOptionPane.showMessageDialog(PanelDeEscritorio, "Ventana Abierta");
	}
    }//GEN-LAST:event_btnGuiasActivasActionPerformed

    private void BtnRubbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRubbersActionPerformed
            
    }//GEN-LAST:event_BtnRubbersActionPerformed

    private void BtnRubbersMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_BtnRubbersMenuSelected
        //InfoRubbers infoRubbers = new InfoRubbers();
         
        if(!infoRubbers.isShowing())
	{   
            PanelDeEscritorio.add(infoRubbers);
            infoRubbers.show();
	}
	else
	{
            JOptionPane.showMessageDialog(PanelDeEscritorio, "Ventana Abierta");
	}
    }//GEN-LAST:event_BtnRubbersMenuSelected

    private void AgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClientesActionPerformed
        
    }//GEN-LAST:event_AgregarClientesActionPerformed

    private void AddClienteEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClienteEmpresaActionPerformed
        
        if(!agregarEmpresaPanel.isShowing())
	{   
            PanelDeEscritorio.add(agregarEmpresaPanel);
            agregarEmpresaPanel.show();
	}
	else
	{
            JOptionPane.showMessageDialog(PanelDeEscritorio, "Ventana Abierta");
	}
        
       
        //empresa.setVisible(true);
    }//GEN-LAST:event_AddClienteEmpresaActionPerformed

    private void BtnRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecepcionActionPerformed
        
    }//GEN-LAST:event_BtnRecepcionActionPerformed

    private void BtnRecepcionMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_BtnRecepcionMenuSelected
        if(!formulario_Recepcion.isShowing())
	{   
            formulario_Recepcion.setVisible(true);
	}
	else
	{
            JOptionPane.showMessageDialog(PanelDeEscritorio, "Ventana Abierta");
	}
        
    }//GEN-LAST:event_BtnRecepcionMenuSelected

    private void BtnCotizarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_BtnCotizarMenuSelected
        if(!detalleCotizarPanel.isShowing())
	{   
            PanelDeEscritorio.add(detalleCotizarPanel);
            detalleCotizarPanel.show();
	}
	else
	{
            JOptionPane.showMessageDialog(PanelDeEscritorio, "Ventana Abierta");
	}
    }//GEN-LAST:event_BtnCotizarMenuSelected

    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMenu().setVisible(true);
            }
        });
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddClienteEmpresa;
    private javax.swing.JMenuItem AddClienteNatural;
    private javax.swing.JMenu AgregarClientes;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu BtnCotizar;
    private javax.swing.JMenu BtnRecepcion;
    private javax.swing.JMenu BtnRubbers;
    private javax.swing.JMenuItem BuscarCliente;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JMenu MenuAlmacen;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuGuias;
    private javax.swing.JDesktopPane PanelDeEscritorio;
    private javax.swing.JMenuItem btnGuiasActivas;
    private javax.swing.JMenuItem btnGuiasCerradas;
    private javax.swing.JMenuItem btnTodasLasGuias;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
